# Generated by Django 5.2 on 2025-04-23 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id_article', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='Publier ?')),
                ('titre', models.CharField(max_length=150, verbose_name="Titre de l'article")),
                ('slug', models.SlugField(default='')),
                ('lead', models.CharField(max_length=50, verbose_name='lead text')),
                ('content', models.TextField(verbose_name='Contenu principal')),
                ('cover', models.ImageField(upload_to='Article_cover_image/', verbose_name='Image de couverture')),
                ('image', models.ImageField(upload_to='Article_main_image/', verbose_name='Image principal')),
                ('cover_alt_text', models.CharField(max_length=125, verbose_name="Texte alternatif pour accessibilité de l'image de couverture")),
                ('image_alt_text', models.CharField(max_length=125, verbose_name="Texte alternatif pour accessibilité de l'image principal")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date Création')),
            ],
        ),
        migrations.CreateModel(
            name='chef',
            fields=[
                ('id_chef', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, verbose_name='Nom Chef')),
                ('prenom', models.CharField(max_length=50, verbose_name='Nom Chef')),
                ('specialite', models.CharField(max_length=150, verbose_name='Rôle')),
                ('image', models.ImageField(upload_to='Chefs_image/', verbose_name='Image chef')),
                ('image_alt_text', models.CharField(max_length=125, verbose_name="Texte alternatif pour accessibilité de l'image")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif ?')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date Création')),
            ],
        ),
        migrations.CreateModel(
            name='contact_company',
            fields=[
                ('id_contact', models.AutoField(primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=50, unique=True, verbose_name='Contact')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date Création')),
            ],
        ),
        migrations.CreateModel(
            name='email_send',
            fields=[
                ('id_message', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, verbose_name='Nom Client')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Client')),
                ('message', models.TextField(verbose_name='Message du Client')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date Création')),
            ],
        ),
        migrations.CreateModel(
            name='liensociale',
            fields=[
                ('id_lien', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=50, unique=True, verbose_name='Nom de la Plateforme')),
                ('lien', models.CharField(max_length=255, verbose_name='lien vers le compte')),
            ],
        ),
        migrations.CreateModel(
            name='liensociale_company',
            fields=[
                ('id_lien', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=50, unique=True, verbose_name='Nom de la Plateforme')),
                ('lien', models.CharField(max_length=255, verbose_name='lien vers le compte')),
            ],
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, verbose_name='Nom Menu')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('image', models.ImageField(upload_to='Menus_image/', verbose_name='Image principal')),
                ('image_alt_text', models.CharField(max_length=125, verbose_name="Texte alternatif pour accessibilité de l'image principal")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif ?')),
                ('pinned', models.BooleanField(default=True, verbose_name='Épingler ?')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date Création')),
            ],
        ),
        migrations.CreateModel(
            name='newsletter_email',
            fields=[
                ('id_new', models.AutoField(primary_key=True, serialize=False)),
                ('email_visteur', models.EmailField(max_length=254, unique=True, verbose_name='Email visiteur')),
                ('actif', models.BooleanField(default=True, verbose_name='actif ?')),
            ],
        ),
        migrations.CreateModel(
            name='service_client',
            fields=[
                ('id_agent', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('actif', models.BooleanField(default=True, verbose_name='Agent actif ?')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date Création')),
            ],
        ),
        migrations.CreateModel(
            name='studio_info',
            fields=[
                ('id_info', models.AutoField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=50, verbose_name='Nom Restaurant')),
                ('app_adresse', models.CharField(max_length=50, verbose_name='Adresse Restaurant')),
                ('app_mapslocation', models.TextField(verbose_name='Adresse Maps')),
                ('app_mailadresse', models.EmailField(max_length=254, verbose_name='Email Restaurant')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date Création')),
            ],
        ),
        migrations.CreateModel(
            name='plat',
            fields=[
                ('id_plat', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, verbose_name='Nom Plat')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='Plats_image/', verbose_name='Image plat')),
                ('image_alt_text', models.CharField(max_length=125, verbose_name="Texte alternatif pour accessibilité de l'image")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif ?')),
                ('pinned', models.BooleanField(default=True, verbose_name='Épingler ?')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date Création')),
                ('id_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monarque.menu')),
            ],
        ),
    ]
