# Generated by Django 5.2 on 2025-04-23 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monarque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liensociale',
            name='id_chef',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='monarque.chef'),
        ),
    ]
