# Generated by Django 5.2 on 2025-04-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monarque', '0002_liensociale_id_chef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Visible ?'),
        ),
        migrations.AlterField(
            model_name='plat',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Visible ?'),
        ),
    ]
