# Generated by Django 5.2 on 2025-04-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monarque', '0004_alter_chef_prenom_alter_liensociale_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_client',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='service_client',
            name='nom',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nom'),
        ),
    ]
