# Generated by Django 5.2 on 2025-04-24 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monarque', '0005_alter_service_client_email_alter_service_client_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='', max_length=150),
        ),
    ]
