# Generated by Django 5.2 on 2025-04-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monarque', '0006_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='lead',
            field=models.CharField(max_length=150, verbose_name='lead text'),
        ),
    ]
