# Generated by Django 5.2 on 2025-05-06 21:51

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monarque', '0007_alter_article_lead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMenu',
            fields=[
                ('id_menu', models.IntegerField(blank=True, db_index=True)),
                ('nom', models.CharField(max_length=50, verbose_name='Nom Menu')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('image', models.TextField(max_length=100, verbose_name='Image principal')),
                ('image_alt_text', models.CharField(max_length=125, verbose_name="Texte alternatif pour accessibilité de l'image principal")),
                ('actif', models.BooleanField(default=True, verbose_name='Visible ?')),
                ('pinned', models.BooleanField(default=True, verbose_name='Épingler ?')),
                ('date_creation', models.DateTimeField(blank=True, editable=False, verbose_name='Date Création')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical menu',
                'verbose_name_plural': 'historical menus',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
