# Generated by Django 5.2 on 2025-05-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monarque', '0009_historicalarticle_historicalchef_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_send',
            name='message',
            field=models.CharField(max_length=255, verbose_name='Message du Client'),
        ),
        migrations.AlterField(
            model_name='historicalemail_send',
            name='message',
            field=models.CharField(max_length=255, verbose_name='Message du Client'),
        ),
    ]
